baseURL = ""
title = "Fleet Halo"
theme = "flewidity"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # 
googleAnalytics = ""  # add your tracking id
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

[params.enable]
 # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = true
    googleMapsApiKey = "AIzaSyDnCjrDpQwQLK4UFpop5EjgIr0jpT-UY_g"

    latitude = "-12.043333"
    longitude = "-77.028333"
    

# - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url

formspree_action = "https://formspree.io/f/xoqgvzkr"
contact_form_ajax = true

    enableRecaptchaInContactForm = true
    googleRecaptchaKey = "site_key_for_google_recaptcha"

# - form actin key set here / Your form's endpoint is:
    formspreekey = "xvonddbb"



# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

[params]
mainSections = ['posts']
lang = "en"
author = ""
description = ""
favicon = "/img/favicon_io/favicon.ico"  # path to a .ico to use as favicon
faviconApple = "/img/favicon_io/apple-touch-icon.png"
favicon32 = "/img/favicon_io/favicon-32x32.png"
favicon16 = "/img/favicon_io/favicon-16x16.png"
manifest = "/img/favicon_io/site.webmanifest"
logo = ""  # url or path to a logo to put in the header
logoImg = "/img/logo-blue_bg.webp"
logoFooterImg = "/img/logo-black_bg.webp"

[params.footer]
text = "© 2024 Fleet Halo - All rights reserved"
url = ""
description = "Driving the future of safe, eco-friendly, and effective connected fleets and assets."

[params.footerInformation]
title = "More Information"

[params.footerContactus]
title = "Contact"
telLink = "8882141051"
tel = "(888) 214-1051"
url = "mailto:info@fleethalo.com"
text = "info@fleethalo.com"


[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/i/flow/login"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "E-mail"
url = "#"

[[params.socialIcons]]
icon = "fab fa-facebook"
title = "facebook"
url = "#"  

[params.recent_posts]
enable = true
title = "Our Blog"
subtitle = "Find Our Latest Post"
hide_summary = false

# Format dates with Go's time formatting
date_format = "Mon, Jan 2, 2006"

[permalinks]
"/" = "/:filename"

# MENU
[menu]
    # Main menu
    [[menu.main]]
    name       = "Solutions"
    identifier = "menu.solutions"
    url        = "/solutions"
    weight     = 1

    [[menu.main]]
    name       = "Industries"
    identifier = "menu.industries"
    url        = "/industries"
    weight     = 2

    [[menu.main]]
    name       = "Our Products"
    identifier = "menu.products"
    url        = "#"
    weight     = 3

    [[menu.main]]
    name = 'Hardware'
    identifier = "menu.products.hardware"
    url = '/products/hardware'
    parent = 'menu.products'
    weight = 1

    [[menu.main]]
    name = 'Software'
    identifier = "menu.products.software"
    url = '/products/software#software-plan'
    parent = 'menu.products'
    weight = 2

    [[menu.main]]
    name = 'Software Plan'
    identifier = "menu.products.software-plan"
    url = '/products/software-plan'
    parent = 'menu.products'
    weight = 3

    [[menu.main]]
    name = 'Marketplace'
    identifier = "menu.products.marketplace"
    url = '/products/marketplace'
    parent = 'menu.products'
    weight = 4

    [[menu.main]]
    name       = "Our Company"
    identifier = "menu.company"
    weight     = 4

    [[menu.main]]
    name = 'About us'
    identifier = "menu.company.about"
    url = '/company/about'
    parent = 'menu.company'
    weight = 1

    [[menu.main]]
    name = 'Contact us'
    identifier = "menu.company.contact"
    url = '/company/contact'
    parent = 'menu.company'
    weight = 2

    # Menu Footer
    [[menu.footer]]
    name       = "Solutions"
    identifier = "menu.solutions"
    url        = "/solutions"
    weight     = 1

    [[menu.footer]]
    name       = "Industries"
    identifier = "menu.industries"
    url        = "/industries"
    weight     = 2

    [[menu.footer]]
    name = 'About us'
    identifier = "menu.company.about"
    url = '/company/about'
    weight = 3

    [[menu.footer]]
    name = 'Contact us'
    identifier = "menu.company.contact"
    url = '/company/contact'
    weight = 4

    [[menu.footer]]
    name       = "Blog"
    identifier = "menu.blog"
    url        = "/posts"
    weight     = 5

[params.heros]
enable = true
title = "A Single Platform for Maximizing Fleet Efficiency"
subtitle = "Access practical insights and suggestions to enhance your fleet's efficiency, safety, and sustainability, all driven by AI and data analytics."
details = "Our smart GPS fleet management system is designed to enhance business productivity and efficiency, while also revealing opportunities for cost reduction"
btnText = "View Subscription Plans"
btnLink = "/products/software-plan/"
linkText = "Get a demo"
linkLink = "/request-demo"

[params.features]
enable = true
title = "What We Do"
subtitle = "Get out of the business of being in the business."
cols = 3 # Default: 3, Available values 2,3,4,6

[params.softwareplans]
enable = true

[params.HomeOverview]
enable = true
title = "Powering safe, sustainable, and efficient connected fleets and assets"
image = "/img/us-device-group-fleettracking.webp"
width = 1400
height = 934
text = "Obtain a detailed, real-time overview of your fleet's daily operations, allowing you to reduce costs, increase productivity, stay ahead of vehicle maintenance, and maximize the efficiency of every business day."

[params.howtouse]
enable = true
title = "Commercial telematics platform global fleets depend on" 

[params.contact]
enable = true
title = "Contact Us" 

[params.trustedpartners]
enable = true
title = "Trusted Partners" 
subtitle = "With our Company, you've got a friend in the tech business. We've built long-term relationships with trusted partners so you don't have to." 

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

# Enable and disable widgets for the right sidebar
[params.widgets]
categories = true
tags = true
search = true


[markup.goldmark.renderer]
unsafe = true  # allow raw HTML in markdown files
